BlueMenta-dark
mate-desktop/mate-themes pull request #310
Opened 2023-11-07 23:31 UTC by 0x0000ff

2023-11-08 03:56 UTC, lukefromdc reviewed
Just installed this for testing. Similar in some ways to adwaita-dark save for black views rather than the dark grey GNOME used-and NOT using symbolic icons by default, a huge plus for many MATE users.. Also proper MATE support that adwaita does not explicitly build in but which we try to cover with same defaults in our applications.

Personally I would have used the dark grey views, a bit easier on the eyes but that's just me. Note that video editing is a common use for dark themes, as many prefer to have the playing clips as the only bright element on-screen. None the less, I'm all for adding this, as it gives another option without adding a lot of maintainance burden as it's a recoloration of BlueMenta. That should mean same bugs and same fixes.

My views may be unique as the UbuntuStudio GTK theme of 2008 vintage and my GTK3 port of it (UbuntuStudio_Legacy)  is a mixed light/dark theme. Audio editing rather than video editing along with still photo work seemed to have been the focus of UbuntuStudio at that time, thus not using a full-dark theme. I have never seen another mixed theme.

2023-11-09 11:44 UTC, raveit65 commented
I prefer the light BlueMenta but the dark variant looks very nice.
With a quick test i see that the unfocuses titlebar text color isn't readable on a dark background.
I think it's `C_title_unfocused` in metacity theme-2/3.
Do you like to maintain the theme?

2024-02-22 18:22 UTC, raveit65 commented
@0x0000ff 
Any news?
To be clear i do not have any free resource to maintain another theme.
So, without a new maintainer i can't add the theme.
But maybe @mate-desktop/core-team has a different opinion

2024-02-25 19:06 UTC, lukefromdc commented
I don't really have additional time to take on maintaining another theme myself. I am also worried about "bus factor" with the political hornet's nest in my country this year

2024-02-25 23:51 UTC, 0x0000ff commented
Hi Luke,

Sorry for the late reply. There are some things I've been meaning to tweak
and I'll have a look at them tomorrow, including the title bar text. I'll
consider requests to do further tweaks to the theme, and fix any discovered
glitches if requested.

One thing of note. The button to restore a maximised window in Firefox does
not show on the light or dark version of this theme.




On Sun, 25 Feb 2024, 19:06 Luke from DC, ***@***.***> wrote:

> I don't really have additional time to take on maintaining another theme
> myself. I am also worried about "bus factor" with the political hornet's
> nest in my country this year
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mate-desktop/mate-themes/pull/310#issuecomment-1963031526>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAPCW6TIYN6AN6NTN4YCQMLYVODT7AVCNFSM6AAAAAA7B7O732VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNRTGAZTCNJSGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-25 23:57 UTC, lukefromdc commented
Firefox is extremely difficult to theme or work on

2024-02-26 22:53 UTC, 0x0000ff commented
Would changing title to black be better? I also adjusted the
highlighting to refine the engraved look. Might do that with the
focused text as well.

On Sun, 2024-02-25 at 15:57 -0800, Luke from DC wrote:


> Firefox is extremely difficult to theme or work on
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: <mate-
> ***@***.***>

2024-02-26 23:33 UTC, 0x0000ff commented
![Screenshot at 2024-02-26 22-50-47](https://github.com/mate-desktop/mate-themes/assets/1977210/d92bb370-7a5f-4c5a-a1b1-8895800dbca8)

2024-02-26 23:50 UTC, 0x0000ff commented
At a further glance, it looks like the 'engraved' look might be the
font being rendered on my lcd screen...

On Sun, 2024-02-25 at 15:57 -0800, Luke from DC wrote:
> Firefox is extremely difficult to theme or work on
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: <mate-
> ***@***.***>

2024-02-29 15:56 UTC, 0x0000ff commented
I also made changes to the focused title text to make the letters have more of an engraved effect.
![Screenshot at 2024-02-29 15-48-33](https://github.com/mate-desktop/mate-themes/assets/1977210/363e4a47-5cf6-41e7-9e33-174c659516dc)

2024-09-07 18:56 UTC, lukefromdc commented
I found one error in this, mate-appearance-properties will show it with
`
(mate-appearance-properties:55838): Gtk-WARNING **: 14:20:19.545: Theme parsing error: gtk-main.css:11:62: Missing semicolon at end of color definition`

line 11 in gtk-main
`
@define-color theme_unfocused_base_color @insensitive_bg_color, 1.015; /* I don't want the same color, hope not to hurt usability to much here */`

Should be

`@define-color theme_unfocused_base_color shade (@insensitive_bg_color, 1.015); /* I don't want the same color, hope not to hurt usability to much here */``

which is the same way bluementa and menta handle thios

2024-09-12 05:23 UTC, lukefromdc commented
I can confirm this fixes the problem, no errors reported here on using the theme with this applied. Waiting for another review since this is a whole new theme and more to maintain

2025-09-08 20:10 UTC, vkareh requested changes
This theme is missing the following files:
- `index.theme.in`
- `Makefile.am` in _all_ directories
- `gtk-3.0/settings.ini.in`

Because of this things end up not properly building and the theme name and translations are all wrong.

2025-10-07 13:23 UTC, vkareh requested changes
This theme is not yet added to the build system. You need to add `BlueMenta-dark` to the `mate-themes/desktop-themes/Makefile.am` file.

2025-10-07 13:23 UTC, vkareh commented on desktop-themes/BlueMenta-dark/index.theme.in
> +Comment=A clean light theme with blue elements
> A clean **dark** theme with blue elements

2025-10-07 13:23 UTC, vkareh commented on desktop-themes/BlueMenta-dark/index.theme
> +[Desktop Entry]
This file is generated and should not be in the repo.

2025-10-07 13:23 UTC, vkareh commented on desktop-themes/BlueMenta-dark/index.theme.in
> +MetacityTheme=BlueMenta
These should both be `BlueMenta-dark`

2025-10-22 17:17 UTC, vkareh requested changes
There are still a few things to resolve. Also the theme files are missing from the `configure.ac`, which means it won't build anyway.

Other than that, I've managed to test the theme locally and it looks great!

2025-10-22 17:17 UTC, vkareh commented on desktop-themes/BlueMenta-dark/gtk-3.0/settings.ini
> +[Settings]
This file is generated - only the `settings.ini.in` file should be tracked in git.

2025-10-22 17:17 UTC, vkareh commented on desktop-themes/BlueMenta-dark/gtk-3.0/chroot.shq
> +/* Default color scheme */
Confused about this file - seems like leftover during development? Should probably be removed.

2025-10-22 17:17 UTC, vkareh commented on desktop-themes/BlueMenta-dark/metacity-1/metacity-theme-3.xml
> +	<name>BlueMenta</name>
Name should be `BlueMenta-dark`

2025-10-22 17:17 UTC, vkareh commented on desktop-themes/BlueMenta-dark/metacity-1/metacity-theme-2.xml
> +    <name>BlueMenta</name>
Name should be `BlueMenta-dark`

2025-10-22 17:17 UTC, vkareh commented on desktop-themes/BlueMenta-dark/metacity-1/metacity-theme-1.xml
> +	<name>BlueMenta</name>
Name should be `BlueMenta-dark`

2025-10-22 17:17 UTC, vkareh commented on desktop-themes/BlueMenta-dark/gtk-3.0/settings.ini.in
> +gtk-color-scheme = "base_color:#f7f7f7\nbg_color:#2b2b2b\ntooltip_bg_color:#F5F5B5\nselected_bg_color:#6699CC\ntext_color:#2c2c2c\nfg_color:#2c2c2c;\ntooltip_fg_color:#2c2c2c\nselected_fg_color:#ffff
These colors don't seem to match the CSS:
```css
theme_base_color #161616;         /* does not match */
theme_bg_color #2b2b2b;
theme_selected_bg_color #6699CC;
theme_text_color #CBCFCD;         /* does not match */
theme_fg_color @theme_text_color;
theme_selected_fg_color #000000;  /* does not match */
```

2025-10-28 14:44 UTC, vkareh approved these changes

2025-10-28 14:45 UTC, merged